# Generated by Django 3.1.6 on 2021-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
